export const mandateProtocolAbi = [
  { type: 'error', name: 'ZeroAddress', inputs: [] },
  { type: 'error', name: 'ZeroAmount', inputs: [] },
  { type: 'error', name: 'UnsupportedToken', inputs: [{ name: 'token', type: 'address' }] },
  { type: 'error', name: 'FeeOnTransferTokenUnsupported', inputs: [] },
  { type: 'error', name: 'InvalidPeriod', inputs: [] },
  { type: 'error', name: 'InvalidChargeLimit', inputs: [] },
  { type: 'error', name: 'InvalidSpendCap', inputs: [] },
  { type: 'error', name: 'PlanNotFound', inputs: [{ name: 'planId', type: 'uint256' }] },
  { type: 'error', name: 'PlanDisabled', inputs: [{ name: 'planId', type: 'uint256' }] },
  { type: 'error', name: 'NotPlanMerchant', inputs: [] },
  { type: 'error', name: 'SubscriptionNotFound', inputs: [{ name: 'subscriptionId', type: 'uint256' }] },
  { type: 'error', name: 'NotSubscriber', inputs: [] },
  { type: 'error', name: 'InvalidSubscriptionStatus', inputs: [] },
  { type: 'error', name: 'ChargeNotDue', inputs: [{ name: 'nextChargeAt', type: 'uint64' }] },
  { type: 'error', name: 'ChargeLimitReached', inputs: [] },
  { type: 'error', name: 'SpendCapExceeded', inputs: [] },
  { type: 'error', name: 'InsufficientVaultBalance', inputs: [
    { name: 'available', type: 'uint256' },
    { name: 'required', type: 'uint256' },
  ] },
  { type: 'error', name: 'ChargesPaused', inputs: [] },
  { type: 'error', name: 'RefundExceedsPaidAmount', inputs: [] },
  {
    type: 'function',
    name: 'deposit',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'withdraw',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'createPlan',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'amountPerPeriod', type: 'uint128' },
      { name: 'periodSeconds', type: 'uint64' },
      { name: 'merchantChargeLimit', type: 'uint32' },
      { name: 'metadataURI', type: 'string' },
    ],
    outputs: [{ name: 'planId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'setPlanEnabled',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'planId', type: 'uint256' },
      { name: 'enabled', type: 'bool' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'subscribe',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'planId', type: 'uint256' },
      { name: 'chargeLimit', type: 'uint32' },
      { name: 'spendCap', type: 'uint128' },
    ],
    outputs: [{ name: 'subscriptionId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'charge',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'subscriptionId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'pauseSubscription',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'subscriptionId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'resumeSubscription',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'subscriptionId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'cancelSubscription',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'subscriptionId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'refund',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'subscriptionId', type: 'uint256' },
      { name: 'amount', type: 'uint128' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'hasActiveAccess',
    stateMutability: 'view',
    inputs: [{ name: 'subscriptionId', type: 'uint256' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'vaultBalance',
    stateMutability: 'view',
    inputs: [
      { name: 'account', type: 'address' },
      { name: 'token', type: 'address' },
    ],
    outputs: [{ name: 'amount', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'plans',
    stateMutability: 'view',
    inputs: [{ name: 'planId', type: 'uint256' }],
    outputs: [
      { name: 'merchant', type: 'address' },
      { name: 'token', type: 'address' },
      { name: 'amountPerPeriod', type: 'uint128' },
      { name: 'periodSeconds', type: 'uint64' },
      { name: 'merchantChargeLimit', type: 'uint32' },
      { name: 'enabled', type: 'bool' },
      { name: 'metadataURI', type: 'string' },
    ],
  },
  {
    type: 'function',
    name: 'subscriptions',
    stateMutability: 'view',
    inputs: [{ name: 'subscriptionId', type: 'uint256' }],
    outputs: [
      { name: 'planId', type: 'uint256' },
      { name: 'subscriber', type: 'address' },
      { name: 'spendCap', type: 'uint128' },
      { name: 'totalSpent', type: 'uint128' },
      { name: 'totalRefunded', type: 'uint128' },
      { name: 'nextChargeAt', type: 'uint64' },
      { name: 'paidUntil', type: 'uint64' },
      { name: 'chargeLimit', type: 'uint32' },
      { name: 'charges', type: 'uint32' },
      { name: 'status', type: 'uint8' },
    ],
  },
  {
    type: 'function',
    name: 'planCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'subscriptionCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'chargesArePaused',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
] as const

export const erc20Abi = [
  {
    type: 'function',
    name: 'approve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'allowance',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'decimals',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'symbol',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
  },
] as const
